# Generated by Django 4.1.7 on 2023-04-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_id', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('release_date', models.DateField()),
                ('video_release_date', models.DateField()),
                ('url', models.CharField(max_length=500)),
                ('genres', models.CharField(max_length=500)),
                ('language', models.CharField(max_length=150)),
                ('avg_rating', models.FloatField()),
            ],
        ),
    ]
