# Generated by Django 4.1.7 on 2023-04-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_release_date',
            field=models.DateField(default=None),
        ),
    ]
