# Generated by Django 4.1.7 on 2023-04-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0003_alter_movie_release_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='avg_rating',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='language',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
