# Generated by Django 4.1.7 on 2023-04-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_interface', '0006_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
